### PR TITLE
Fix #21 allowing an array to be returned from a controller.

### LINKED ISSUE #21: Returning an array from a controller results in a MissingMappingsException
If you return an array from a controller (instead of say a List<T>) the JsonApiActionFilter will throw a MissingMappingsException. This occurs as the element type of the array is not reflected (the code only handles classes that are assignable to IEnumerable<T>).

A pretty minor thing but easy to fix :)

### PR DESCRIPTION
**Pull request by burgessl**
Also fixed up the tests project and added tests for Reflection.cs

### CODE REVIEW

**Comment by brainwipe** [comment]
Please ignore the travis CI, it's gone nuts.

**Comment by brainwipe** [comment]
@burgessl Thank you for this! 

It's going to be tomorrow/Friday before I can test this and put together a release. Do you need this urgently?

**Comment by burgessl** [comment]
Woops commented on the issue not the PR - no urgency to this at all as it can always be worked around by using a sensible generic collection instead.

**Review by brainwipe — APPROVED** [review]
Great!

**Pull request merged**
