### PR TITLE
Fixed model binding bug for POST/PATCH requests

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by brainwipe** [comment]
This is great, thank you! The new filter is definitely the better way to do it. I think I'll get a chance to give it a test tomorrow.

**Comment by brainwipe** [comment]
Thank you for the PR. The unit tests needed fixing but that was all!

**Comment by ghost** [comment]
Thanks! Do you know when this fix will be released?

**Comment by brainwipe** [comment]
No problem. I can put a fix together this week. Do you need it fast?

**Comment by ghost** [comment]
This week is fine. I have copied the two resource files in my project for now.

**Pull request merged**
